In [4]:
import numpy as np

#### **Basic Array creation**

In [5]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [6]:
a = [1,2,3,4.5]
a

[1, 2, 3, 4.5]

In [7]:
np.array(a)

array([1. , 2. , 3. , 4.5])

In [8]:
l = [[1,2,3], [4,5,6], [7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### **Array generation function**

**np.arange(strt,end)** => this function creates array of numbers given between these ranges 

In [10]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**np.zeros((row , colm))** => creates two dimension matrix of zeros(0) with the given rows and coloumns

In [11]:
arr = np.zeros((4,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

**np.ones((row , colm))** => creates two dimension matrix of one(1) with the given rows and coloumns

In [12]:
arr = np.ones((4,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

**np.linspace()** -> Linear space between range , 
linspace(1,5,3) => from 1 to 5 with  linear space gives 3 numbers 

In [13]:
arr = np.linspace(1,5,3)
arr

array([1., 3., 5.])

In [14]:
arr = np.linspace(1,10,50)
arr

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

#### **Random Generation Function**

In [15]:
arr = np.random.rand(5)
arr

array([0.84657252, 0.98274587, 0.26844309, 0.56357396, 0.67633968])

**np.random.rand()** => random.rand() function generates arrays of random number between 1 to 0 -> **Normalization**
but 
random.randn() function creates arrays of random number between -3 to 3 called **Statardisation**

In [16]:
arr = np.random.randn(10)
arr

array([ 0.00409906, -0.76587878, -1.11770032,  0.21132735,  0.20621775,
        1.26864449,  0.90826856, -1.14318192,  0.98119402, -0.00202127])

In [17]:
arr = np.random.randint(1,10,10)
arr

array([9, 2, 4, 1, 1, 3, 1, 4, 7, 7], dtype=int32)

#### **Array Atributes**

In [18]:
arr = np.array([[1,2,3],[4,5,6], [7,8,9], [12,34,56]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [12, 34, 56]])

**shape** -> it describes the shape means (rows,coloumns)of an array

In [19]:
arr.shape

(4, 3)

In [20]:
arr.size

12

In [21]:
arr.dtype

dtype('int64')

#### **Array Methods**

In [22]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [12, 34, 56]])

In [23]:
arr.min()

np.int64(1)

In [24]:
arr.max()

np.int64(56)

In [25]:
arr.sum()

np.int64(147)

In [26]:
np.sum(arr,axis=0)

array([24, 49, 74])

In [29]:
np.sum(arr, axis=1)

array([  6,  15,  24, 102])

In [30]:
arr.mean()

np.float64(12.25)

In [31]:
arr.std()

np.float64(15.59981303306763)

In [32]:
arr.argmin()

np.int64(0)

In [33]:
arr.argmax()

np.int64(11)

#### **Reshaping and Resizing**

In [34]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [35]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])