In [3]:
import numpy as np

#### Numpy Indexing and slicing of Vectors

In [5]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [6]:
arr[4]

np.int64(15)

In [7]:
arr[0:11]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

**arr[str : end : step]** 

In [8]:
arr[::2]

array([11, 13, 15, 17, 19])

#### Numpy Indexing and slicing of Matrix

In [9]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [17]:
arr[0]

array([1, 2, 3, 4, 5])

In [20]:
arr[0,0]

np.int64(1)

In [22]:
slice = arr[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

In [24]:
arr[3:6,3:5]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [28]:
colum = arr[:,3]
colum

array([ 4,  9, 14, 19, 24, 29])

#### Boolean Indexing

In [29]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [30]:
bool_index = arr %2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [31]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])